import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProviders } from "./providers/chakraProviders";
import StoreProvider from "./providers/StoreProvider";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brainspark Lab",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <StoreProvider>
          <ChakraProviders>{children}</ChakraProviders>
        </StoreProvider>
      </body>
    </html>
  );
}
